version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    command: python app.py

  front:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
